"""
Multi-stream temporal classifier for sign language recognition.

This module implements the architecture described in the provided flow chart:

RGB Frames -> Landmark extraction -> (Body, Hand, Face streams)
-> Normalization + per-stream TCN encoders (kernel=3, dilations 1/2/4)
-> Feature concatenation + projection
-> xLSTM stack (mLSTM or sLSTM variants)
-> Temporal attention pooling
-> Classification head

The model operates purely on keypoint sequences, making it compatible with
the JSON outputs generated by ``sign_detector.py``.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, Optional, Sequence, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F


# ---------------------------------------------------------------------------
# Utility configs
# ---------------------------------------------------------------------------


@dataclass
class StreamConfig:
    """Configuration for an individual keypoint stream."""

    input_dim: int
    hidden_dim: int
    dropout: float = 0.1
    kernel_size: int = 3
    dilations: Sequence[int] = (1, 2, 4)


@dataclass
class XlstmConfig:
    """Configuration for the xLSTM stack."""

    hidden_dims: Sequence[int] = (256, 256)
    variant: str = "mlstm"  # or "slstm"
    dropout: float = 0.1
    bidirectional: bool = False  # only effective for sLSTM


# ---------------------------------------------------------------------------
# Temporal convolution (TCN) components
# ---------------------------------------------------------------------------


class TemporalConvBlock(nn.Module):
    """A residual temporal convolution block with dilation."""

    def __init__(
        self,
        channels: int,
        kernel_size: int = 3,
        dilation: int = 1,
        dropout: float = 0.1,
    ) -> None:
        super().__init__()
        padding = (kernel_size - 1) * dilation // 2
        self.conv1 = nn.Conv1d(
            channels, channels, kernel_size, padding=padding, dilation=dilation
        )
        self.conv2 = nn.Conv1d(
            channels, channels, kernel_size, padding=padding, dilation=dilation
        )
        self.norm1 = nn.BatchNorm1d(channels)
        self.norm2 = nn.BatchNorm1d(channels)
        self.activation = nn.GELU()
        self.dropout = nn.Dropout(dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        residual = x
        out = self.conv1(x)
        out = self.norm1(out)
        out = self.activation(out)
        out = self.dropout(out)

        out = self.conv2(out)
        out = self.norm2(out)
        out = self.activation(out)
        out = self.dropout(out)
        return out + residual


class TemporalConvEncoder(nn.Module):
    """Stack of TemporalConvBlocks using the requested dilations."""

    def __init__(
        self,
        channels: int,
        kernel_size: int = 3,
        dilations: Sequence[int] = (1, 2, 4),
        dropout: float = 0.1,
    ) -> None:
        super().__init__()
        blocks = []
        for dilation in dilations:
            blocks.append(
                TemporalConvBlock(
                    channels=channels,
                    kernel_size=kernel_size,
                    dilation=dilation,
                    dropout=dropout,
                )
            )
        self.blocks = nn.Sequential(*blocks)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.blocks(x)


class StreamEncoder(nn.Module):
    """Normalization + projection + TCN encoder for a single stream."""

    def __init__(self, config: StreamConfig) -> None:
        super().__init__()
        self.norm = nn.LayerNorm(config.input_dim)
        self.projection = nn.Linear(config.input_dim, config.hidden_dim)
        self.tcn = TemporalConvEncoder(
            channels=config.hidden_dim,
            kernel_size=config.kernel_size,
            dilations=config.dilations,
            dropout=config.dropout,
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x: Tensor shaped [batch, time, features]
        Returns:
            Tensor shaped [batch, time, hidden_dim]
        """
        x = self.norm(x)
        x = self.projection(x)
        x = x.transpose(1, 2)  # [B, C, T]
        x = self.tcn(x)
        return x.transpose(1, 2)


# ---------------------------------------------------------------------------
# xLSTM implementations
# ---------------------------------------------------------------------------


class MultiplicativeLSTMCell(nn.Module):
    """Multiplicative LSTM cell (Krause et al., 2016)."""

    def __init__(self, input_dim: int, hidden_dim: int) -> None:
        super().__init__()
        self.hidden_dim = hidden_dim
        self.xh = nn.Linear(input_dim, hidden_dim * 4)
        self.hh = nn.Linear(hidden_dim, hidden_dim * 4)
        self.xm = nn.Linear(input_dim, hidden_dim)
        self.hm = nn.Linear(hidden_dim, hidden_dim)

    def forward(
        self, x: torch.Tensor, state: Tuple[torch.Tensor, torch.Tensor]
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        h_prev, c_prev = state
        m_t = torch.tanh(self.xm(x) * self.hm(h_prev))
        gates = self.xh(x) + self.hh(m_t)
        i, f, o, g = torch.chunk(gates, 4, dim=-1)

        i = torch.sigmoid(i)
        f = torch.sigmoid(f)
        o = torch.sigmoid(o)
        g = torch.tanh(g)

        c_t = f * c_prev + i * g
        h_t = o * torch.tanh(c_t)
        return h_t, c_t


class XlstmLayer(nn.Module):
    """Single xLSTM layer supporting multiplicative or standard variants."""

    def __init__(
        self,
        input_dim: int,
        hidden_dim: int,
        variant: str = "mlstm",
        dropout: float = 0.1,
        bidirectional: bool = False,
    ) -> None:
        super().__init__()
        variant = variant.lower()
        if variant not in {"mlstm", "slstm"}:
            raise ValueError("variant must be 'mlstm' or 'slstm'")

        self.variant = variant
        self.hidden_dim = hidden_dim
        self.bidirectional = bidirectional and variant == "slstm"
        self.dropout = nn.Dropout(dropout)

        if variant == "mlstm":
            if bidirectional:
                raise ValueError("Multiplicative LSTM is only implemented for 1 direction.")
            self.cell = MultiplicativeLSTMCell(input_dim, hidden_dim)
        else:
            self.rnn = nn.LSTM(
                input_dim,
                hidden_dim,
                num_layers=1,
                batch_first=True,
                bidirectional=self.bidirectional,
            )

    def forward(
        self, x: torch.Tensor, lengths: Optional[torch.Tensor] = None
    ) -> torch.Tensor:
        """
        Args:
            x: [batch, time, dim]
            lengths: optional [batch] lengths for masking (slstm only)
        Returns:
            Tensor shaped [batch, time, hidden*directions]
        """
        if self.variant == "mlstm":
            return self._forward_mlstm(x)
        return self._forward_slstm(x, lengths)

    def _forward_mlstm(self, x: torch.Tensor) -> torch.Tensor:
        batch, time, _ = x.shape
        h_t = x.new_zeros(batch, self.hidden_dim)
        c_t = x.new_zeros(batch, self.hidden_dim)
        outputs = []
        for t in range(time):
            h_t, c_t = self.cell(x[:, t, :], (h_t, c_t))
            outputs.append(h_t.unsqueeze(1))
        out = torch.cat(outputs, dim=1)
        return self.dropout(out)

    def _forward_slstm(
        self, x: torch.Tensor, lengths: Optional[torch.Tensor]
    ) -> torch.Tensor:
        if lengths is not None:
            packed = nn.utils.rnn.pack_padded_sequence(
                x, lengths.cpu(), batch_first=True, enforce_sorted=False
            )
            packed_out, _ = self.rnn(packed)
            out, _ = nn.utils.rnn.pad_packed_sequence(
                packed_out, batch_first=True, total_length=x.size(1)
            )
        else:
            out, _ = self.rnn(x)
        return self.dropout(out)


class XlstmStack(nn.Module):
    """Stack of xLSTM layers."""

    def __init__(
        self,
        input_dim: int,
        config: XlstmConfig,
    ) -> None:
        super().__init__()
        layers = []
        prev_dim = input_dim
        for hidden_dim in config.hidden_dims:
            layers.append(
                XlstmLayer(
                    input_dim=prev_dim,
                    hidden_dim=hidden_dim,
                    variant=config.variant,
                    dropout=config.dropout,
                    bidirectional=config.bidirectional,
                )
            )
            directions = 2 if config.bidirectional and config.variant == "slstm" else 1
            prev_dim = hidden_dim * directions
        self.layers = nn.ModuleList(layers)
        self.output_dim = prev_dim

    def forward(
        self, x: torch.Tensor, lengths: Optional[torch.Tensor] = None
    ) -> torch.Tensor:
        for layer in self.layers:
            x = layer(x, lengths)
        return x


# ---------------------------------------------------------------------------
# Temporal pooling
# ---------------------------------------------------------------------------


class TemporalAttentionPooling(nn.Module):
    """Scaled dot-product attention pooling using a learned query vector."""

    def __init__(self, input_dim: int, attn_dim: int = 128) -> None:
        super().__init__()
        self.proj = nn.Sequential(
            nn.LayerNorm(input_dim),
            nn.Linear(input_dim, attn_dim),
            nn.Tanh(),
        )
        self.attn = nn.Linear(attn_dim, 1)

    def forward(
        self,
        x: torch.Tensor,
        lengths: Optional[torch.Tensor] = None,
        return_weights: bool = False,
    ) -> Tuple[torch.Tensor, Optional[torch.Tensor]]:
        """
        Args:
            x: [batch, time, dim]
            lengths: optional [batch] valid lengths for masking
        """
        scores = self.attn(self.proj(x)).squeeze(-1)  # [B, T]
        if lengths is not None:
            mask = (
                torch.arange(x.size(1), device=x.device)
                .unsqueeze(0)
                .expand(x.size(0), -1)
            )
            mask = mask >= lengths.unsqueeze(1)
            scores = scores.masked_fill(mask, float("-inf"))
        weights = torch.softmax(scores, dim=-1).unsqueeze(-1)  # [B, T, 1]
        pooled = torch.sum(weights * x, dim=1)
        if return_weights:
            return pooled, weights.squeeze(-1)
        return pooled, None


# ---------------------------------------------------------------------------
# Full multi-stream classifier
# ---------------------------------------------------------------------------


class MultiStreamSignClassifier(nn.Module):
    """End-to-end classifier built from the provided architecture."""

    def __init__(
        self,
        body_stream: StreamConfig,
        hand_stream: StreamConfig,
        face_stream: StreamConfig,
        num_classes: int,
        fusion_dim: int = 512,
        xlstm_config: Optional[XlstmConfig] = None,
        attn_dim: int = 128,
        final_dropout: float = 0.2,
    ) -> None:
        super().__init__()
        self.body_encoder = StreamEncoder(body_stream)
        self.hand_encoder = StreamEncoder(hand_stream)
        self.face_encoder = StreamEncoder(face_stream)

        encoder_dim = (
            body_stream.hidden_dim
            + hand_stream.hidden_dim
            + face_stream.hidden_dim
        )
        self.fusion = nn.Sequential(
            nn.LayerNorm(encoder_dim),
            nn.Linear(encoder_dim, fusion_dim),
            nn.GELU(),
        )

        xlstm_config = xlstm_config or XlstmConfig()
        self.xlstm = XlstmStack(fusion_dim, xlstm_config)
        self.temporal_pool = TemporalAttentionPooling(
            self.xlstm.output_dim, attn_dim=attn_dim
        )

        self.classifier = nn.Sequential(
            nn.LayerNorm(self.xlstm.output_dim),
            nn.Dropout(final_dropout),
            nn.Linear(self.xlstm.output_dim, num_classes),
        )

    def forward(
        self,
        inputs: Dict[str, torch.Tensor],
        lengths: Optional[torch.Tensor] = None,
        return_attention: bool = False,
    ) -> Dict[str, torch.Tensor]:
        """
        Args:
            inputs: dict with ``body``, ``hand``, and ``face`` tensors of shape [B, T, F]
            lengths: optional valid lengths [B] for variable-length batches
            return_attention: if True, include attention weights in the output dict
        Returns:
            dict containing ``logits`` and intermediate tensors.
        """
        missing = {k for k in ("body", "hand", "face") if k not in inputs}
        if missing:
            raise KeyError(f"Missing required input streams: {missing}")

        body_feat = self.body_encoder(inputs["body"])
        hand_feat = self.hand_encoder(inputs["hand"])
        face_feat = self.face_encoder(inputs["face"])

        fused = torch.cat([body_feat, hand_feat, face_feat], dim=-1)
        fused = self.fusion(fused)

        contextual = self.xlstm(fused, lengths)
        pooled, attn_weights = self.temporal_pool(
            contextual, lengths, return_weights=return_attention
        )
        logits = self.classifier(pooled)

        output = {
            "logits": logits,
            "pooled": pooled,
            "contextual": contextual,
        }
        if return_attention:
            output["attention_weights"] = attn_weights
        return output


# ---------------------------------------------------------------------------
# Convenience factory
# ---------------------------------------------------------------------------


def build_default_classifier(
    num_body_joints: int,
    num_hand_joints: int,
    num_face_joints: int,
    num_classes: int,
    coordinate_dims: int = 3,
    **kwargs,
) -> MultiStreamSignClassifier:
    """
    Helper to quickly instantiate the classifier with sensible defaults.

    Args:
        num_body_joints: e.g., 17 for COCO-format pose
        num_hand_joints: e.g., 42 (21 per hand concatenated)
        num_face_joints: e.g., 478 for MediaPipe face mesh
        coordinate_dims: 2 for (x, y) or 3 for (x, y, confidence/z)
        num_classes: output vocabulary size
        kwargs: forwarded to ``MultiStreamSignClassifier``
    """
    body_dim = num_body_joints * coordinate_dims
    hand_dim = num_hand_joints * coordinate_dims
    face_dim = num_face_joints * coordinate_dims

    body_cfg = StreamConfig(input_dim=body_dim, hidden_dim=256)
    hand_cfg = StreamConfig(input_dim=hand_dim, hidden_dim=192)
    face_cfg = StreamConfig(input_dim=face_dim, hidden_dim=256)

    return MultiStreamSignClassifier(
        body_stream=body_cfg,
        hand_stream=hand_cfg,
        face_stream=face_cfg,
        num_classes=num_classes,
        **kwargs,
    )


# ---------------------------------------------------------------------------
# Demo
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    batch_size, time_steps = 2, 64
    dummy_inputs = {
        "body": torch.randn(batch_size, time_steps, 17 * 3),
        "hand": torch.randn(batch_size, time_steps, 42 * 3),
        "face": torch.randn(batch_size, time_steps, 478 * 3),
    }
    model = build_default_classifier(
        num_body_joints=17,
        num_hand_joints=42,
        num_face_joints=478,
        num_classes=200,
    )
    outputs = model(dummy_inputs)
    print("Logits shape:", outputs["logits"].shape)
